# Generated by Django 4.2.5 on 2023-10-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_centers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={"ordering": ("first_name",)},
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_appointment",
        ),
        migrations.AddField(
            model_name="breed",
            name="breed_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/breeds/"),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("specialist", "visit_date", "visit_time"),
                name="unique_appointment",
                violation_error_message="The meeting with this specialist on this time has been already appointed.",
            ),
        ),
    ]
