# Generated by Django 4.2.5 on 2023-10-02 13:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import training_centers.models


class Migration(migrations.Migration):
    dependencies = [
        ("training_centers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[training_centers.models.validate_positive_price],
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+123456789'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="years_of_experience",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="training_centers.service",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="training_centers.specialist",
                    ),
                ),
                (
                    "training_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="training_centers.trainingcenter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-visit_date",),
            },
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("specialist", "visit_date"), name="unique_appointment"
            ),
        ),
    ]
