# Generated by Django 4.2.5 on 2023-10-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_centers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
