# Generated by Django 4.2.5 on 2023-10-05 01:30

from django.db import migrations, models
import training_centers.models


class Migration(migrations.Migration):
    dependencies = [
        ("training_centers", "0002_alter_specialist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="age",
            field=models.PositiveIntegerField(
                validators=[training_centers.models.validate_years]
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                validators=[training_centers.models.validate_years]
            ),
        ),
    ]
